### ISSUE TITLE
Might be a little literal mistake

### ISSUE THREAD

**Issue by hybcloud** [ThomasJowett/Cross-Platform-Game-Engine#1]
There defined a function at `src/Scene/Scene.cpp` line 38 which is named `CopyComponentIfExits`.
According to the context, I guess it should be `CopyComponentIfExist` instead.

**Comment by ThomasJowett** [comment]
well spotted, thank you!
fixed in [this commit](https://github.com/ThomasJowett/Cross-Platform-Game-Engine/commit/f948e30dcf3fbaae4d63ff1d64c8c70f455fa583)
